user:
  age: 18
  sex: female
version: 1.1.0
debug: true

# Redis 配置
redis:
  host: ${REDIS_HOST} # redis 地址，默认 127.0.0.1:6379
  port: ${REDIS_PORT} # redis 端口，默认 6379
  password: ${REDIS_PASSWORD} # redis 密码
  #addrs:
  #master-name: # redis 集群 master 名称
  #username: # redis 登录用户名
  #database: # redis 数据库
  #optimisation-max-idle:  # redis 连接池中的最大空闲连接数
  #optimisation-max-active: # 最大活跃连接数
  #timeout: # 连接 redis 时的超时时间
  #enable-cluster: # 是否开启集群模式
  #use-ssl: # 是否启用 TLS
  #ssl-insecure-skip-verify: # 当连接 redis 时允许使用自签名证书
